a = input('Digite algp: ')
print('O tipo primitivo', type(a))
print('so tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Está em maiúculas?', a.isupper())
print('Está em minusculas?', a.islower())
print('Está em capitalizada?', a.istitle())